services:
  # postgres:
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=valuepostgres
  #   ports:
  #     - "5433:5433"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/var/lib/mongo/data
volumes:
  # pgdata:
  mongodata: